      INTEGER MXDIM
      PARAMETER (MXDIM = 50)
      COMMON /BASE1/ XL(MXDIM),XU(MXDIM),NDIM,NWILD,
     .               IG(MXDIM),NCALL
      DOUBLE PRECISION XL,XU
      INTEGER NDIM,NWILD,IG,NCALL
      SAVE /BASE1/
