      INTEGER ITM
      PARAMETER (ITM = 50)
      COMMON /BASE5/ ITRAT(ITM,0:1),TIME(ITM,0:2),EFF(ITM,0:1),
     .               WRONG(ITM,0:1),RESLT(ITM,0:1),ACSTD(ITM,0:1),
     .               TRSLT(ITM,0:1),TSTD(ITM,0:1),PCNT(ITM,0:1)
      INTEGER ITRAT
      REAL TIME,EFF,WRONG,TRSLT,TSTD,PCNT
      DOUBLE PRECISION RESLT,ACSTD
      SAVE /BASE5/
