      DOUBLE PRECISION XLT,XUT,ACC1T,ACC2T
      INTEGER NDIMT,NWILDT,IGT,NCALLT,ITMX1T,ITMX2T
      COMMON /BPARM1/ XLT(MXDIM),XUT(MXDIM),NDIMT,NWILDT,
     .                IGT(MXDIM),NCALLT
      COMMON /BPARM2/ ACC1T,ACC2T,ITMX1T,ITMX2T
      SAVE /BPARM1/,/BPARM2/
