      INTEGER NHS,NSC
      PARAMETER ( NHS = 50, NSC = 50 )
      INTEGER XHASH,DHASH,NHIST,MAPL,IFBASE,NSCAT,MAPD,NW
      COMMON/PLOTH/ XHASH(NHS+1,13),DHASH(NSC+1,14),IFBASE(NHS),
     .              NHIST, MAPL(4,NHS),
     .              NSCAT, MAPD(4,NSC),
     .              NW
      INTEGER IBUF
      COMMON /PLOTB/ IBUF( 281*NHS + 2527*NSC )
      REAL           BUFF( 281*NHS + 2527*NSC )
      EQUIVALENCE (IBUF(1),BUFF(1))
      INTEGER LU
      COMMON/PLOTLU/ LU
      SAVE /PLOTH/,/PLOTB/,/PLOTLU/
